# Generated by Django 5.0.3 on 2024-03-12 20:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Админ'), ('florist', 'Флорист'), ('currier', 'Курьер')], max_length=40, verbose_name='Роль')),
                ('start_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата начала работы')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата увольнения')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
            },
        ),
    ]
