# Generated by Django 5.0.3 on 2024-03-17 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='tg_id',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Телеграм id'),
        ),
    ]
