# Generated by Django 5.0.3 on 2024-03-12 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultingStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Статус консультации',
                'verbose_name_plural': 'Статусы консультаций',
            },
        ),
        migrations.CreateModel(
            name='Occasion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Повод')),
            ],
            options={
                'verbose_name': 'Повод',
                'verbose_name_plural': 'Поводы',
            },
        ),
        migrations.CreateModel(
            name='Consulting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('contact_phone', models.CharField(max_length=40, verbose_name='Контактный телефон')),
                ('first_call_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата и время звонка')),
                ('florist', models.ForeignKey(limit_choices_to={'role': 'florist'}, on_delete=django.db.models.deletion.PROTECT, related_name='consultings', to='account.staff', verbose_name='Флорист')),
            ],
            options={
                'verbose_name': 'Консультация',
                'verbose_name_plural': 'Консультации',
            },
        ),
        migrations.CreateModel(
            name='ConsultingStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('consulting', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='status_history', to='flower_shop.consulting', verbose_name='Консультация')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='status_history', to='flower_shop.consultingstatus', verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'История статусов консультации',
                'verbose_name_plural': 'Истории статусов консультаций',
            },
        ),
        migrations.AddField(
            model_name='consulting',
            name='status',
            field=models.ManyToManyField(through='flower_shop.ConsultingStatusHistory', to='flower_shop.consultingstatus'),
        ),
        migrations.AddField(
            model_name='consulting',
            name='occasion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consultings', to='flower_shop.occasion', verbose_name='Повод'),
        ),
        migrations.CreateModel(
            name='Bouquet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='bouquets', verbose_name='Изображение')),
                ('name', models.CharField(max_length=40, verbose_name='Название букета')),
                ('description', models.TextField(verbose_name='Описание')),
                ('content', models.TextField(verbose_name='Состав')),
                ('price', models.PositiveIntegerField(verbose_name='Цена')),
                ('occasion', models.ManyToManyField(related_name='bouquets', to='flower_shop.occasion', verbose_name='Повод')),
            ],
            options={
                'verbose_name': 'Букет',
                'verbose_name_plural': 'Букеты',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, choices=[('new', 'Новый'), ('processing', 'В работе'), ('ready', 'Готов'), ('delivered', 'Доставлен'), ('canceled', 'Отменен')], max_length=40, null=True, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('delivery_date', models.DateTimeField(verbose_name='Дата доставки')),
                ('delivery_address', models.CharField(max_length=200, verbose_name='Адрес доставки')),
                ('contact_phone', models.CharField(max_length=20, verbose_name='Контактный телефон')),
                ('contact_name', models.CharField(max_length=40, verbose_name='Контактное лицо')),
                ('bouquet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='flower_shop.bouquet', verbose_name='Букет')),
                ('consultation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='flower_shop.consulting', verbose_name='Консультация')),
                ('currier', models.ForeignKey(blank=True, limit_choices_to={'role': 'currier'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='account.staff', verbose_name='Курьер')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
    ]
