# Generated by Django 5.0.3 on 2024-03-13 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flower_shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bouquet',
            name='is_recommended',
            field=models.BooleanField(default=False, verbose_name='Рекомендуемый'),
        ),
    ]
