# Generated by Django 5.0.3 on 2024-03-14 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flower_shop', '0002_bouquet_is_recommended'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryInterval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField(verbose_name='Время начала')),
                ('end_time', models.TimeField(verbose_name='Время окончания')),
            ],
            options={
                'verbose_name': 'Интервал доставки',
                'verbose_name_plural': 'Интервалы доставки',
            },
        ),
        migrations.CreateModel(
            name='PaymentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Тип оплаты')),
            ],
            options={
                'verbose_name': 'Тип оплаты',
                'verbose_name_plural': 'Типы оплаты',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='ealiest_delivery',
            field=models.BooleanField(default=False, verbose_name='Ранняя доставка'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_date',
            field=models.DateField(verbose_name='Дата доставки'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_interval',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='flower_shop.deliveryinterval', verbose_name='Интервал доставки'),
        ),
    ]
