# Generated by Django 5.0.3 on 2024-03-14 15:51

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flower_shop', '0004_order_is_paid_order_payment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulting',
            name='contact_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Контактный телефон'),
        ),
    ]
