# Generated by Django 5.0.3 on 2024-03-14 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('flower_shop', '0005_alter_consulting_contact_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulting',
            name='florist',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'florist'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='consultings', to='account.staff', verbose_name='Флорист'),
        ),
    ]
