# Generated by Django 5.0.3 on 2024-03-14 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flower_shop', '0006_alter_consulting_florist'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulting',
            name='client_name',
            field=models.CharField(default='Нет имени', max_length=100, verbose_name='Имя клиента'),
        ),
    ]
