# Generated by Django 5.0.3 on 2024-03-14 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flower_shop', '0007_consulting_client_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consultingstatushistory',
            old_name='created_at',
            new_name='status_created_at',
        ),
    ]
