# Generated by Django 5.0.3 on 2024-03-14 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flower_shop', '0009_alter_consulting_client_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consulting',
            name='status',
        ),
    ]
