# Generated by Django 5.0.3 on 2024-03-14 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flower_shop', '0010_remove_consulting_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulting',
            name='agreement',
            field=models.BooleanField(default=False, verbose_name='Согласие на обработку персональных данных'),
        ),
    ]
