# Generated by Django 5.0.3 on 2024-03-15 08:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flower_shop', '0011_consulting_agreement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulting',
            name='occasion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='consultings', to='flower_shop.occasion', verbose_name='Повод'),
        ),
    ]
