# Generated by Django 5.0.3 on 2024-03-15 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flower_shop', '0004_alter_order_delivery_date'),
        ('flower_shop', '0012_alter_consulting_occasion'),
    ]

    operations = [
    ]
