# Generated by Django 5.0.3 on 2024-03-15 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flower_shop', '0013_merge_20240315_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultingstatushistory',
            name='consulting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='flower_shop.consulting', verbose_name='Консультация'),
        ),
    ]
